# Generated by Django 4.2.7 on 2025-10-04 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TukacodleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tukacodle_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-score', 'created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
