# Generated by Django 5.0.1 on 2025-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tukacodlescore'),
    ]

    operations = [
        # Add indexes for frequently queried fields
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-elo_score'], name='api_photo_elo_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['uploader', '-elo_score'], name='api_photo_user_elo_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['-voted_at'], name='api_vote_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', '-voted_at'], name='api_vote_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_vote_date'], name='api_profile_votedate_idx'),
        ),
        migrations.AddIndex(
            model_name='tukacodlescore',
            index=models.Index(fields=['date', '-score'], name='api_tukacodle_date_score_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='api_message_conv_read_idx'),
        ),
    ]
