# Generated by Django 4.2.7 on 2025-10-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_conv_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='api_photo_elo_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='api_photo_user_elo_idx',
        ),
        migrations.RemoveIndex(
            model_name='tukacodlescore',
            name='api_tukacodle_date_score_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='api_profile_votedate_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='api_vote_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='api_vote_user_date_idx',
        ),
        migrations.AddField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
