# Generated by Django 4.2.7 on 2025-10-05 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_add_file_hash_to_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tukacodlescore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tukacodlescore',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='tukacodlescore',
            unique_together={('user', 'date', 'attempt_number')},
        ),
    ]
